/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    dodatki: Dodatki;
    zasoby: Zasoby;
    rezerwacje: Rezerwacje;
    blokady: Blokady;
    platnosci: Platnosci;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    dodatki: DodatkiSelect<false> | DodatkiSelect<true>;
    zasoby: ZasobySelect<false> | ZasobySelect<true>;
    rezerwacje: RezerwacjeSelect<false> | RezerwacjeSelect<true>;
    blokady: BlokadySelect<false> | BlokadySelect<true>;
    platnosci: PlatnosciSelect<false> | PlatnosciSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'ustawienia-strony': UstawieniaStrony;
    'ustawienia-rezerwacji': UstawieniaRezerwacji;
  };
  globalsSelect: {
    'ustawienia-strony': UstawieniaStronySelect<false> | UstawieniaStronySelect<true>;
    'ustawienia-rezerwacji': UstawieniaRezerwacjiSelect<false> | UstawieniaRezerwacjiSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  typPliku?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dodatki".
 */
export interface Dodatki {
  id: number;
  name: string;
  /**
   * Wybierz, dla jakiego typu zasobu ten dodatek ma być dostępny.
   */
  dostepneDla: ('przyczepa' | 'ebike')[];
  /**
   * Kwota w PLN (np. 50.00).
   */
  price: number;
  pricingType: 'perBooking' | 'perDay';
  maxQuantity: number;
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zasoby".
 */
export interface Zasoby {
  id: number;
  typZasobu: 'przyczepa' | 'ebike';
  nazwa: string;
  slug?: string | null;
  /**
   * Jeśli wyłączone — nie pokazuj w ofercie / rezerwacjach.
   */
  active: boolean;
  /**
   * Jeśli zaznaczone, zasób może pojawić się w sekcji Polecane na stronie głównej (max 3).
   */
  featured?: boolean | null;
  /**
   * Ile egzemplarzy tego zasobu faktycznie posiadasz.
   */
  iloscSztuk: number;
  opisKrotki?: string | null;
  opisDlugi?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroMedia: number | Media;
  gallery?:
    | {
        media: number | Media;
        id?: string | null;
      }[]
    | null;
  specyfikacja?:
    | {
        label: string;
        value: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  cena: {
    /**
     * Przyczepy zwykle: noc. Rower: dzień.
     */
    jednostka: 'noc' | 'dzien';
    /**
     * Cena za jednostkę (noc/dzień).
     */
    basePrice: number;
    seasonalPricing?:
      | {
          name: string;
          dateFrom: string;
          dateTo: string;
          price: number;
          /**
           * Minimum nocy/dni w tym sezonie.
           */
          minUnits?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Dodatki, które można wybrać przy rezerwacji tego zasobu.
   */
  dodatki?: (number | Dodatki)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rezerwacje".
 */
export interface Rezerwacje {
  id: number;
  /**
   * Generowany automatycznie przy utworzeniu rezerwacji.
   */
  reservationNumber?: string | null;
  zasob: number | Zasoby;
  /**
   * Ile sztuk zasobu jest rezerwowanych (np. 2 rowery). Dla przyczepy zwykle 1.
   */
  ilosc: number;
  startDate: string;
  endDate: string;
  /**
   * Wyliczane automatycznie. Dla e-bike: endDate - 1.
   */
  returnDate?: string | null;
  status: 'pending_payment' | 'deposit_paid' | 'paid' | 'confirmed' | 'cancelled';
  extras?:
    | {
        dodatek: number | Dodatki;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  klient: {
    fullName: string;
    email: string;
    phone: string;
    /**
     * Wymagane dla przyczepy (jeśli przyczepa jest podstawiana pod adres klienta).
     */
    deliveryAddress?: string | null;
    deliveryDetails?: string | null;
    deliveryGps?: string | null;
    wantsInvoice?: boolean | null;
    /**
     * Wybierz typ faktury, jeśli zaznaczono „Faktura”.
     */
    invoiceType?: ('none' | 'personal' | 'company') | null;
    companyName?: string | null;
    companyAddress?: string | null;
    /**
     * Wymagany, jeśli faktura jest na firmę.
     */
    nip?: string | null;
    notes?: string | null;
    disability?: boolean | null;
  };
  payment?: {
    payableNow?: number | null;
    paidAmount?: number | null;
    dueAmount?: number | null;
    paidInFull?: boolean | null;
  };
  /**
   * Pola wyliczane automatycznie
   */
  snapshot?: {
    units?: number | null;
    unitType?: string | null;
    basePrice?: number | null;
    breakdown?:
      | {
          label: string;
          units: number;
          pricePerUnit: number;
          total: number;
          id?: string | null;
        }[]
      | null;
    extrasSnapshot?:
      | {
          name: string;
          pricingType: 'perBooking' | 'perDay';
          unitPrice: number;
          quantity: number;
          total: number;
          id?: string | null;
        }[]
      | null;
    serviceFee?: number | null;
    total?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blokady".
 */
export interface Blokady {
  id: number;
  zasob: number | Zasoby;
  dateFrom: string;
  dateTo: string;
  ilosc: number;
  komunikat?: string | null;
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platnosci".
 */
export interface Platnosci {
  id: number;
  booking: number | Rezerwacje;
  provider: 'stripe' | 'p24';
  providerSessionId?: string | null;
  transactionId?: string | null;
  amount: number;
  currency: string;
  status: 'created' | 'pending' | 'succeeded' | 'failed' | 'refunded';
  paidAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'dodatki';
        value: number | Dodatki;
      } | null)
    | ({
        relationTo: 'zasoby';
        value: number | Zasoby;
      } | null)
    | ({
        relationTo: 'rezerwacje';
        value: number | Rezerwacje;
      } | null)
    | ({
        relationTo: 'blokady';
        value: number | Blokady;
      } | null)
    | ({
        relationTo: 'platnosci';
        value: number | Platnosci;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  typPliku?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dodatki_select".
 */
export interface DodatkiSelect<T extends boolean = true> {
  name?: T;
  dostepneDla?: T;
  price?: T;
  pricingType?: T;
  maxQuantity?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zasoby_select".
 */
export interface ZasobySelect<T extends boolean = true> {
  typZasobu?: T;
  nazwa?: T;
  slug?: T;
  active?: T;
  featured?: T;
  iloscSztuk?: T;
  opisKrotki?: T;
  opisDlugi?: T;
  heroMedia?: T;
  gallery?:
    | T
    | {
        media?: T;
        id?: T;
      };
  specyfikacja?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  cena?:
    | T
    | {
        jednostka?: T;
        basePrice?: T;
        seasonalPricing?:
          | T
          | {
              name?: T;
              dateFrom?: T;
              dateTo?: T;
              price?: T;
              minUnits?: T;
              id?: T;
            };
      };
  dodatki?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rezerwacje_select".
 */
export interface RezerwacjeSelect<T extends boolean = true> {
  reservationNumber?: T;
  zasob?: T;
  ilosc?: T;
  startDate?: T;
  endDate?: T;
  returnDate?: T;
  status?: T;
  extras?:
    | T
    | {
        dodatek?: T;
        quantity?: T;
        id?: T;
      };
  klient?:
    | T
    | {
        fullName?: T;
        email?: T;
        phone?: T;
        deliveryAddress?: T;
        deliveryDetails?: T;
        deliveryGps?: T;
        wantsInvoice?: T;
        invoiceType?: T;
        companyName?: T;
        companyAddress?: T;
        nip?: T;
        notes?: T;
        disability?: T;
      };
  payment?:
    | T
    | {
        payableNow?: T;
        paidAmount?: T;
        dueAmount?: T;
        paidInFull?: T;
      };
  snapshot?:
    | T
    | {
        units?: T;
        unitType?: T;
        basePrice?: T;
        breakdown?:
          | T
          | {
              label?: T;
              units?: T;
              pricePerUnit?: T;
              total?: T;
              id?: T;
            };
        extrasSnapshot?:
          | T
          | {
              name?: T;
              pricingType?: T;
              unitPrice?: T;
              quantity?: T;
              total?: T;
              id?: T;
            };
        serviceFee?: T;
        total?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blokady_select".
 */
export interface BlokadySelect<T extends boolean = true> {
  zasob?: T;
  dateFrom?: T;
  dateTo?: T;
  ilosc?: T;
  komunikat?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platnosci_select".
 */
export interface PlatnosciSelect<T extends boolean = true> {
  booking?: T;
  provider?: T;
  providerSessionId?: T;
  transactionId?: T;
  amount?: T;
  currency?: T;
  status?: T;
  paidAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ustawienia-strony".
 */
export interface UstawieniaStrony {
  id: number;
  siteName: string;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ustawienia-rezerwacji".
 */
export interface UstawieniaRezerwacji {
  id: number;
  dlaPrzyczep: {
    enabled: boolean;
    minUnits?: number | null;
    serviceFee?: number | null;
    paymentMode?: ('full' | 'deposit') | null;
    depositType?: ('percent' | 'fixed') | null;
    /**
     * Jeśli procent: np. 30 = 30%. Jeśli kwota: wartość w PLN.
     */
    depositValue?: number | null;
  };
  dlaRowerow: {
    enabled: boolean;
    minUnits?: number | null;
    serviceFee?: number | null;
    paymentMode?: ('full' | 'deposit') | null;
    depositType?: ('percent' | 'fixed') | null;
    /**
     * Jeśli procent: np. 30 = 30%. Jeśli kwota: wartość w PLN.
     */
    depositValue?: number | null;
  };
  regulaminPdf?: (number | null) | Media;
  politykaPrywatnosciPdf?: (number | null) | Media;
  paymentProviderDefault: 'stripe' | 'p24';
  faq?:
    | {
        question: string;
        answer: string;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ustawienia-strony_select".
 */
export interface UstawieniaStronySelect<T extends boolean = true> {
  siteName?: T;
  phone?: T;
  email?: T;
  address?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ustawienia-rezerwacji_select".
 */
export interface UstawieniaRezerwacjiSelect<T extends boolean = true> {
  dlaPrzyczep?:
    | T
    | {
        enabled?: T;
        minUnits?: T;
        serviceFee?: T;
        paymentMode?: T;
        depositType?: T;
        depositValue?: T;
      };
  dlaRowerow?:
    | T
    | {
        enabled?: T;
        minUnits?: T;
        serviceFee?: T;
        paymentMode?: T;
        depositType?: T;
        depositValue?: T;
      };
  regulaminPdf?: T;
  politykaPrywatnosciPdf?: T;
  paymentProviderDefault?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}